version: "3.9"

services:
  db:
    image: mysql:8
    restart: always
    container_name: db
    environment:
      MYSQL_DATABASE: boilerplate
      MYSQL_HOST: 127.0.0.1
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    options: >-
      --health-cmd="mysqladmin ping"
      --health-interval=10s
      --health-timeout=5s
      --health-retries=3
  api:
    image: api
    environment:
      DATABASE_URL: "mysql://admin:password@127.0.0.1:3306/boilerplate"
    ports:
      - "3333:3333"
    depends_on:
      - db
