name: CI
env:
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: boilerplate
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: admin
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    env:
      DATABASE_URL: "mysql://admin:password@127.0.0.1:3306/boilerplate"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: "master"
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npx nx affected --target=build --prod --parallel --max-parallel=3
      - name: Migrate
        run: npx prisma migrate deploy
      - name: Test
        run: npx nx affected --target=test --parallel --max-parallel=2
